# Generated by Django 4.1.3 on 2022-11-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessions",
            name="codesession",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
