# Generated by Django 4.1.3 on 2022-11-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="codeService",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name="Posseder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idEmploye",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.reponse",
                    ),
                ),
                (
                    "idService",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.question",
                    ),
                ),
            ],
        ),
    ]
