# Generated by Django 4.1.3 on 2022-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="quiz", name="idSession",),
        migrations.AlterField(
            model_name="quiz",
            name="lienXml",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(name="Posseder",),
    ]
