# Generated by Django 4.1.3 on 2022-11-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_service_codeservice_posseder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posseder",
            name="idEmploye",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.employe"
            ),
        ),
        migrations.AlterField(
            model_name="posseder",
            name="idService",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.service"
            ),
        ),
    ]
