# Generated by Django 4.1.3 on 2022-11-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Employe",),
        migrations.DeleteModel(name="Service",),
    ]
